const Map<String, Map<String, List<String>>> pakistanGeography = {
  'Islamabad Capital': {
    'Islamabad': [
      '12th Avenue',
      '7th Avenue',
      '9th Avenue',
      'AGHOSH',
      'Abdullah Garden',
      'Agha Shahi Avenue',
      'Agro Farming Scheme',
      'Ahmed Town',
      'Airline Avenue',
      'Airport Avenue Housing Society',
      'Airport Enclave',
      'Aiza Garden',
      'Akbar Town',
      'Al Huda Town',
      'Al Qaim Town',
      'Alhamra Avenue',
      'Ali Pur',
      'Alipur Farash',
      'Arsalan Town',
      'Ataturk Avenue',
      'Athal',
      'Atomic Energy Employee Society',
      'Azmat Town',
      'B-17',
      'Bahria Town',
      'Bani Gala',
      'Bhara kahu',
      'Blue Area',
      'Bokra Road',
      'Burma Town',
      'C-14',
      'C-18',
      'C-19',
      'CBR Town',
      'Capital Enclave',
      'Central Avenue',
      'Chak Shahzad',
      'Chatha Bakhtawar',
      'Chattar',
      'Chirah',
      'City Garden',
      'Club Road',
      'D-12',
      'D-13',
      'D-14',
      'D-17',
      'D-18',
      'DHA Defence',
      'Dhok Chaudhrian',
      'Diplomatic Enclave',
      'E-11',
      'E-12',
      'E-14',
      'E-16',
      'E-18',
      'E-7',
      'Emaar Canyon Views',
      'Embassy Road',
      'Engineering Co-operative Housing (ECHS)',
      'F-10',
      'F-11',
      'F-15',
      'F-17',
      'F-6',
      'F-7',
      'F-8',
      'F-9',
      'FECHS',
      'Faisal Town - F-18',
      'Fateh Jang Road',
      'Federal Government Employees Housing Foundation',
      'Frash Town',
      'G-10',
      'G-11',
      'G-12',
      'G-13',
      'G-14',
      'G-15',
      'G-16',
      'G-5',
      'G-6',
      'G-7',
      'G-8',
      'G-9',
      'GT Road',
      'Garden Town',
      'Ghauri Town',
      'Golra Mor',
      'Golra Road',
      'Green Avenue',
      'Green Hills Housing Scheme',
      'Gulberg',
      'Gulshan-e-Khudadad',
      'H-11',
      'H-12',
      'H-13',
      'H-15',
      'H-8',
      'H-9',
      'I-10',
      'I-11',
      'I-12',
      'I-13',
      'I-14',
      'I-16',
      'I-8',
      'I-9',
      'IJP Road',
      'Ibn-e-Sina Road',
      'Iqbal Town',
      'Islamabad - Murree Expressway',
      'Islamabad Enclave',
      'Islamabad Expressway',
      'Islamabad Highway',
      'Islamabad View Valley',
      'Islamabad, Islamabad Capital',
      'Jagiot Road',
      'Japan Road',
      'Jhang Syedan',
      'Jhangi Syedan',
      'Jinnah Avenue',
      'Judicial Town',
      'Kahuta Road',
      'Kahuta Triangle Industrial Area',
      'Karakoram Diplomatic Enclave',
      'Karakoram Enclave 1',
      'Kashmir Highway',
      'Khanna Pul',
      'Khayaban-e-Iqbal',
      'Koral Chowk',
      'Koral Town',
      'Korang Road',
      'Korang Town',
      'Kuri',
      'Kuri Model Town',
      'Kuri Road',
      'Lawyers Society',
      'Lehtarar Road',
      'Madina Town',
      'Malot',
      'Malpur',
      'Margalla Town',
      'Marwa Town',
      'Meherban Colony',
      'Model Town',
      'Motorway Chowk',
      'Multi Residencia & Orchards',
      'Mumtaz City',
      'Murree Road',
      'NHA Housing Society',
      'NIH Colony',
      'National Police Foundation',
      'National Police Foundation O-9',
      'National Town',
      'Naval Anchorage',
      'Naval Farms Housing Scheme',
      'Nazim-ud-din Road',
      'New Airport Town',
      'New Shakrial',
      'OPF Valley',
      'Orchard Scheme',
      'Others',
      'PAEC Employees Cooperative Housing Society',
      'PAF Tarnol',
      'PECHS',
      'PTV Colony',
      'PWD Housing Scheme',
      'PWD Road',
      'Pakistan Intelligence Bureau Housing Society',
      'Pakistan Town',
      'Park Enclave',
      'Park Road',
      'Park View City',
      'Partal Town',
      'Phulgran',
      'Pindorian',
      'Pir Sohawa',
      'Police Foundation Housing Society',
      'Qutbal Town',
      'Raja Akhtar Road',
      'Rawal Enclave',
      'Rawal Town',
      'River Garden',
      'Royal Avenue',
      'Royal City',
      'Sangjani',
      'Sarai Kharbuza',
      'Sehala Farm House',
      'Shah Allah Ditta',
      'Shah Dara',
      'Shaheen Town',
      'Shahpur',
      'Shehzad Town',
      'Sihala',
      'Sihala Valley',
      'Simly Dam Road',
      'Soan Garden',
      'Sohan Valley',
      'Spring Valley',
      'Swan Garden',
      'Taramrri',
      'Tarlai',
      'Tarnol',
      'Thalian',
      'Thanda Pani',
      'The Springs',
      'Top City 1',
      'Tumair',
      'University Town',
      'Victoria Heights',
      'Wapda Town',
      'Zaraj Housing Scheme',
      'Zero Point',
      'Zone 5',
    ],
  },
  'Punjab': {
    'Faisalabad': [
      '204 Chak Road',
      'Abbaspur',
      'Abdullah City',
      'Abdullahpur',
      'Afghanabad',
      'Ahmadabad',
      'Air Avenue City',
      'Akbar Chowk',
      'Akbar Colony',
      'Al Barkat Villas',
      'Al Fayaz Colony',
      'Al Jameel Housing Scheme',
      'Al Masoom Town',
      'Al Najaf Colony',
      'Al Noor Garden',
      'Al Rehmat Villas',
      'Ali Garden',
      'Ali Housing Colony',
      'Ali Town',
      'Allama Iqbal Colony',
      'Amin Town',
      'Amir Town',
      'Aqsa Town',
      'Ayub Colony',
      'Baba Fareed Road',
      'Babuwala',
      'Bakar Mandi Road',
      'Bawa Chack 120 JB',
      'Bilal Nagar',
      'Bilal Road',
      'Burj Mandi',
      'Canal Expressway',
      'Canal Garden',
      'Canal Park',
      'Canal Road',
      'Canal View Hosuing Scheme',
      'Chak 208 RB Dogranwala',
      'Chak 208 Road',
      'Chak 209 RB Akalgarh',
      'Chak 279/RB Kalan',
      'Chak 8 JB Punj Garain',
      'Chak Bahga',
      'Chak Jhumra',
      'Chen One Road',
      'Chenab Gardens',
      'Chibban',
      'Circular Road',
      'Citi Housing Society',
      'Civil Lines',
      'College Road',
      'D Ground',
      'D Type Colony',
      'Daewoo Road',
      'Daniyal Town',
      'Defence Fort Housing Scheme',
      'Dhandharan Chak 66 JB',
      'Dhanola',
      'Dhudi Wala',
      'Diglus Pura',
      'Dijkot Road',
      'Dilawar Colony',
      'Eden Gardens',
      'Eden Orchard',
      'Eden Valley',
      'Eid Gah Road',
      'FDA City',
      'Faisal Gardens',
      'Faisal Town',
      'Faisal Valley',
      'Faisalabad Sangla Hill Road',
      'Faisalabad, Punjab',
      'Fareed Town',
      'Farooqabad',
      'Four Season Housing',
      'GTS Chowk',
      'Garden Colony',
      'Garden Town',
      'Gatwala Chowk',
      'Gatwala Park Road',
      'Ghalib City',
      'Ghulam Mohammad Abad',
      'Gobind Pura',
      'Green Town',
      'Green View Colony',
      'Gulbahar Colony',
      'Gulberg',
      'Gulberg Valley',
      'Gulfishan Colony',
      'Gulgasht Colony',
      'Gulistan Colony No 1',
      'Gulistan Colony No 2',
      'Gulshan Colony',
      'Gulshan Rehman',
      'Gulshan e Madina',
      'Gulshan-E-Iqbal',
      'Gulshan-e-Ali Housing Scheme',
      'Gulshan-e-Habib',
      'Gulshan-e-Haram',
      'Gulshan-e-Hayat',
      'Gulshan-e-Rafique',
      'Gulshan-e-Rehman',
      'Gulzar Colony',
      'Guru Nanak Pura',
      'Haji Abad',
      'Hajveeri Town',
      'Hamza Villas',
      'Harchan Pura',
      'Hassan Villas',
      'Hilal Road',
      'Himat Pura',
      'Ideal Town',
      'Ilahi Abad',
      'Illahi Abad',
      'Imran Road',
      'Iqbal Town',
      'Islamia Park',
      'Ismail City',
      'Ismail Green Valley',
      'Ismail Valley',
      'Jail Road',
      'Jameel Town',
      'Jaranwala',
      'Jaranwala Road',
      'Jaranwala Town',
      'Jhaal Chowk',
      'Jhang Bazar',
      'Jhang Road',
      'Jhumra Road',
      'Jinnah Colony',
      'Johar Colony',
      'Judicial Employees Coop Housing Society',
      'Kaleem Shaheed Colony No 1',
      'Kaleem Shaheed Colony No 2',
      'Kamal Abad',
      'Kareem City',
      'Kareem Garden',
      'Karim Town',
      'Kashmir Road',
      'Kehkishan Colony No 1',
      'Kehkishan Colony No 2',
      'Khalid Abad',
      'Khawaja Gardens',
      'Khawaja Islam Road',
      'Khayaban Colony',
      'Khayaban Colony 2',
      'Khayaban Gardens',
      'Khayaban-e-Manzoor',
      'Khurianwala',
      'Khurrianwala Town',
      'Kiran Villas',
      'Kohinoor City',
      'Kohinoor Town',
      'Lahore - Sheikhupura - Faisalabad Road',
      'Lalazar',
      'Lasani Garden',
      'Lasani Town',
      'Latif Garden',
      'Lawyers Housing Society',
      'Liaqat Road',
      'Liaquat Town',
      'Lower Canal Road',
      'Lyallpur Town',
      'Madan Pura',
      'Madina Gardens',
      'Madina Town',
      'Mahmoodabad',
      'Makkah Commercial Market',
      'Makkah Garden',
      'Manawala',
      'Mansoorabad',
      'Mediacom Avenue',
      'Mian Zulfiqar Ali Shahid Road',
      'Millat Chowk',
      'Millat Road',
      'Millat Town',
      'Model Town',
      'Mohammad Nagar',
      'Motorway City',
      'Munianwala',
      'Murababad',
      'Muslim Town',
      'Muzaffar Colony',
      'Narwala Road',
      'Naveed Garden',
      'Nawaban Wala',
      'Nazimabad',
      'Nazimabad Villas',
      'Nemat Colony No 1',
      'Nemat Colony No 2',
      'New Garden Town',
      'New Green Town',
      'Niamuana Bypass Road',
      'Nighabanpura',
      'Nisar Colony',
      'Nishatabad',
      'Officers Colony',
      'Others',
      'Paradise Valley',
      'Partab Nagar',
      'Peoples Colony No 1',
      'Peoples Colony No 2',
      'Punjab Govt. Servants Housing Foundation',
      'Punjab Small Industries Estate',
      'Qamar Garden',
      'Qasim Abad',
      'Quaid-e-Azam Park',
      'Rabbani Colony',
      'Rachna Town',
      'Raheem Gardens',
      'Railway Road',
      'Raja Colony',
      'Raja Park',
      'Rasheed Nagar',
      'Rasool Nagar',
      'Rasool Park',
      'Ravi Gardens',
      'Raza Abad',
      'Raza Garden',
      'Rehman Gardens',
      'Rehman Pura',
      'Rehman Town',
      'Rehman Villas',
      'Rehmania Town',
      'Riaz ul Jannah',
      'Ryaz ul Jannah',
      'SMD Homes',
      'Saddar',
      'Saeed Colony',
      'Sahianwala',
      'Saifabad',
      'Samanabad',
      'Samanabad Road',
      'Samundari Road',
      'Santpura',
      'Sargodha Road',
      'Satellite Town',
      'Satiana Road',
      'Shadab Colony',
      'Shadman Colony',
      'Shahbaz Town',
      'Shahzad Colony',
      'Shalimar Park',
      'Sheikh Colony',
      'Siddiqia Mill Colony',
      'Sir Syed Town',
      'Sitara Colony',
      'Sitara Sapna City',
      'Sitara Supreme City',
      'Sitara Valley',
      'Steam Power Station Colony',
      'Suhail Abad',
      'Susan Road',
      'Taj Colony',
      'Tandlianwala Town',
      'Tariqabad',
      'Tezab Mill Road',
      'Umair Town',
      'Umer Garden',
      'Umer Valley',
      'University Town',
      'Usman Town',
      'Valencia Gardens',
      'Vista Homes',
      'Wapda City',
      'Wapda Town',
      'Waris Pura',
      'Yasrab Colony',
      'Younas Town',
      'Yousaf Town',
      'Zia Colony',
      'Zubair Colony',
      'Zulfiqar Colony',
    ],
    'Lahore': [
      'AR Cottages',
      'AWT Army Welfare Trust',
      'Aabpara Coop Housing Society',
      'Aashiana Road',
      'Abdali Road',
      'Abdalians Cooperative Housing Society',
      'Abdul Sattar Edhi Road',
      'Abdullah Town',
      'Abid Market',
      'Abu Alkhair Road',
      'Acro Green - Bankers Avenue',
      'Adan Villas',
      'Afzal Park',
      'Agrics Town',
      'Ahbab Colony',
      'Ahlu Road',
      'Ahmad Avenue',
      'Ahmad Housing Society',
      'Airline Housing Society',
      'Airport Road',
      'Aitchison Society',
      'Al Faisal Town',
      'Al Fajar Society',
      'Al Hafeez Gardens',
      'Al Hamad Colony',
      'Al Hamra Town',
      'Al Haram Garden',
      'Al Jalil Garden',
      'Al Jannat Housing Scheme',
      'Al Kareem Garden',
      'Al Madina Avenue',
      'Al Noor Town',
      'Al Raheem Town',
      'Al Rahim Homes',
      'Al Rehman Garden',
      'Al-Amin Housing Society',
      'Al-Falah Cooperative Housing Society',
      'Al-Hafeez Garden Road',
      'Al-Hafiz Town',
      'Al-Hamad Colony (AIT)',
      'Al-Hamd Garden',
      'Al-Hamd Park',
      'Al-Jannat Housing Society - Kahna',
      'Al-Kabir Town',
      'Al-Kareem Premier Housing Scheme',
      'Al-Raheem Garden',
      'Al-Raziq Garden',
      'Al-Wahab Garden - Phase 1',
      'Alfalah Town',
      'Ali Alam Garden',
      'Ali Town',
      'Ali View Garden',
      'Ali View Park',
      'Alia Town',
      'Allama Iqbal Intl Airport',
      'Allama Iqbal Road',
      'Allama Iqbal Town',
      'Alpha Society',
      'Altaf Colony',
      'Aman Town',
      'Ameen Park',
      'Ameer-ud-Din Park',
      'Amina Park',
      'Anarkali',
      'Angoori Bagh',
      'Architects Engineers Housing Society',
      'Ashiana-e-Quaid Housing Scheme',
      'Ashraf Garden',
      'Ashrafi Town',
      'Asif Colony',
      'Asif Town',
      'Asim Town',
      'Askari',
      'Atari Saroba',
      'Audit & Accounts Housing Society',
      'Awan Town',
      'Azadi Chowk',
      'Azam Gardens',
      'Azeem Garden Shahdara',
      'BOR - Board of Revenue Housing Society',
      'Babu Sabu',
      'Badami Bagh',
      'Bagarian',
      'Baghbanpura',
      'Bahadurabad',
      'Bahar Colony',
      'Bahar Shah Road',
      'Bahria Education & Medical City',
      'Bahria Nasheman',
      'Bahria Orchard',
      'Bahria Town',
      'Bait-ul-Raza Colony',
      'Band Road',
      'Bankers Co-operative Housing Society',
      'Bankers Town',
      'Batapur',
      'Beacon House Society',
      'Beadon Road',
      'Bedian Road',
      'Begampura',
      'Begum Kot',
      'Bhagatpura',
      'Bhaini Road',
      'Bhatta Chowk',
      'Bhatti Colony',
      'Bhogiwal',
      'Bhogiwal Road',
      'Bilal Gunj',
      'Birdwood Road',
      'Bismillah Housing Scheme',
      'Budduke Manak Road',
      'Canal Bank Housing Scheme',
      'Canal Burg',
      'Canal Fort II',
      'Canal Garden',
      'Canal View',
      'Canalberg Housing Society',
      'Cantt',
      'Cantt View Society',
      'Cavalry Ground',
      'Central Park Housing Scheme',
      'Chah Miran',
      'Chaman Park',
      'Chauburji',
      'Chauburji Chowk',
      'Chauburji Park Road',
      'Chaudhary Colony',
      'Chaudhary Park',
      'China Scheme',
      'Chinar Bagh',
      'Chohan Road',
      'Chungi Amar Sadhu',
      'Civil Defence',
      'Clifton Colony',
      'College Road',
      'Combo Colony',
      'Cooper Road',
      'Country Homes',
      'Crescent Town',
      'Cricketer Villas',
      'DHA 11 Rahbar',
      'DHA City',
      'DHA Defence',
      'Daroghewala',
      'Dars Baray Mian',
      'Data Darbar Road',
      'Data Ganj Bakhsh Town',
      'Davis Road',
      'Defence Fort',
      'Defence Garden',
      'Defence Road',
      'Dharampura',
      'Dholanwal',
      'Divine Gardens',
      'Divine Homes',
      'Doctors Housing Society',
      'Dogech',
      'Dream Avenue Lahore',
      'Dream Villas',
      'Dubai Town',
      'Dubban Pura',
      'EME Society',
      'Eden',
      'Eden Avenue Extension',
      'Eden Park',
      'Eden Place Housing Scheme',
      'Eden Villas',
      'Education Town',
      'Elite Town',
      'Empress Road',
      'Excise & Taxation Housing Scheme',
      'Expo Avenue Society',
      'Faisal Ghuman Road',
      'Faisal Town',
      'Faiz Bagh',
      'Farid Court Road',
      'Farooq Colony',
      'Fateh Garh',
      'Fateh Villas',
      'Fazaia Housing Scheme',
      'Ferozepur City',
      'Ferozepur Road',
      'Firdous Colony',
      'Formanites Housing Scheme',
      'Fort Villas',
      'GOR',
      'GT Road',
      'Gajju Matah',
      'Garden Town',
      'Garhi Shahu',
      'Garrison Homes',
      'Gawala Colony',
      'Gawalmandi',
      'Ghalib Colony',
      'Ghausia Colony',
      'Ghaziabad',
      'Ghous Garden',
      'Gohawa',
      'Gosha-e-Ahbab',
      'Government Employees Cooperative Housing Society (GECHS)',
      'Government Transport Headquarters Cooperative Housing Society',
      'Grand Avenues Housing Scheme',
      'Green Acres Housing Society',
      'Green Cap Housing Society',
      'Green City',
      'Green Fort',
      'Green Park',
      'Green Park Society',
      'Green Town',
      'Gujjar Colony',
      'Gujjarpura',
      'Gul Colony',
      'Gul Kali',
      'Gul-e-Damin',
      'Gulbahar Colony',
      'Gulbahar Park',
      'Gulberg',
      'Guldasht Town',
      'Gulfishan Colony',
      'Gulfishan Town',
      'Gulistan Colony',
      'Gulnishan Park',
      'Gulshan Colony',
      'Gulshan Farooq Scheme',
      'Gulshan Park',
      'Gulshan View Residence Society',
      'Gulshan-E-Mustafa Housing Society',
      'Gulshan-e-Ahbab',
      'Gulshan-e-Lahore',
      'Gulshan-e-Ravi',
      'Gulshan-e-Riaz',
      'Gulshan-e-Yaseen Housing Society',
      'Gulzar E Ahbab Society',
      'HBFC Housing Society',
      'Habib Homes',
      'Habibullah Road',
      'Haji Park Housing Scheme',
      'Hajvery Housing Scheme',
      'Hakim Town',
      'Hall Road',
      'Hameedpura',
      'Hamza Town',
      'Hanif Park Harbanspura',
      'Hanjarwal',
      'Harbanspura',
      'Harbanspura Road',
      'Hassan Town',
      'Heaven Homes',
      'Heir',
      'Highcourt Society',
      'Hudiara',
      'IBL Housing Scheme',
      'IEP Engineers Town',
      'Ibrahim Colony',
      'Ichhra',
      'Immad Garden Housing Scheme',
      'Infantry Road',
      'Inmol Society',
      'Iqbal Avenue',
      'Iqbal Park',
      'Irrigation Cooperative Housing Society',
      'Islam Nagar',
      'Islamabad Colony',
      'Islamia Park',
      'Islampura',
      'Ittehad Colony',
      'Ittifaq Town',
      'Izmir Town',
      'Jaffar Town',
      'Jaffaria Colony',
      'Jail Road',
      'Jalal Colony',
      'Jalal Pura',
      'Jallo',
      'Jallo Park Road',
      'Jamal Homes',
      'Jamil Town',
      'Jan Muhammad Road',
      'Jaranwala Road',
      'Jati Umra Road',
      'Javed Colony - Ghazi Road',
      'Jewa Town',
      'Jia Baga Road',
      'Jinnah Colony',
      'Johar Town',
      'Jora Pull',
      'Jubilee Town',
      'Judicial Colony',
      'Kacha Ferozepur Road',
      'Kacha Jail Road',
      'Kacha Lawrence Road',
      'Kacha Road',
      'Kachupura',
      'Kahna',
      'Kahna Kacha',
      'Kakezai Housing Society',
      'Kala Khatai Road',
      'Kalma Chowk',
      'Kamahan Road',
      'Karbath',
      'Karim Park',
      'Katar Bund Road',
      'Khaira',
      'Khana Kacha Road',
      'Kharak',
      'Khawaja Ahmed Hassan Road',
      'Khayaban-e-Amin',
      'Khayaban-e-Jinnah Road',
      'Khayaban-e-Quaid',
      'Khayaban-e-Zohra',
      'Khokhar Town',
      'Kot Khawaja Saeed',
      'Kot Lakhpat',
      'Kotli Abdur Rahman',
      'Krishan Nagar',
      'LDA Avenue',
      'LDA City',
      'Labor Colony',
      'Lahore - Islamabad Motorway',
      'Lahore - Jaranwala Road',
      'Lahore - Kasur Road',
      'Lahore Canal Bank Cooperative Housing Society',
      'Lahore Cantt Coop Housing',
      'Lahore Garden Housing Scheme',
      'Lahore Medical Housing Society',
      'Lahore Motorway City',
      'Lahore Press Club Housing Scheme',
      'Lahore Villas',
      'Lahore, Punjab',
      'Lake City',
      'Lakhodher',
      'Lakshmi Chowk',
      'Lalazaar Garden',
      'Lalazar',
      'Land Breeze Housing Society',
      'Lawrence Road',
      'Liaquatabad',
      'Lower Mall',
      'Lytton Road',
      'Madar-e-Millat Road',
      'Madina Colony',
      'Madina Homes',
      'Madina Town',
      'Mahmood Road',
      'Main Canal Bank Road',
      'Makkah Colony',
      'Makki Complex',
      'Malik Park',
      'Malipura',
      'Mall Road',
      'Manawan',
      'Manga - Raiwind Road',
      'Manga Mandi',
      'Mansoorah',
      'Manzoor Colony',
      'Marghzar Officers Colony',
      'Maryam Town',
      'Mason Road',
      'Mateen Avenue',
      'Mateen Garden',
      'Maulana Shaukat Ali Road',
      'Mayo Gardens',
      'McLeod Road',
      'Mehar Fayaz Colony',
      'Meharpura',
      'Mehmood Booti',
      'Meraj Park',
      'Mian Amiruddin Park',
      'Mian Aziz Garden',
      'Mian Colony',
      'Mian Mir Colony',
      'Military Accounts Housing Society',
      'Millat Colony',
      'Millat Road',
      'Misri Shah',
      'Model Colony',
      'Model Town',
      'Mohafiz Town',
      'Mohlanwal',
      'Mohlanwal Road',
      'Mohlanwal Scheme',
      'Mohni Road',
      'Mominpur',
      'Mominpura Road',
      'Montgomery Road',
      'Mozang',
      'Mughalpura',
      'Multan Road',
      'Munir Garden',
      'Muqaddas Park',
      'Mushtaq Park - Phase 3',
      'Muslim Nagar Housing Scheme',
      'Muslim Town',
      'Mustafa Abad',
      'Mustafa Town',
      'NFC 1',
      'NFC 2',
      'Nabha Road',
      'Nabi Pura',
      'Nadeem Shaheed Road',
      'Nadeem Town',
      'Nai Abadi Harbanspura',
      'Nain Sukh',
      'Nasheman-e-Iqbal',
      'Nasirabad',
      'National Town',
      'Nawab Town',
      'Nayyab Villas',
      'Naz Town',
      'Nazir Garden Society',
      'Neela Gumbad',
      'New Canal Park',
      'New Chauburji Park',
      'New Muslim Town',
      'New Samanabad',
      'New Shah Kamal Colony',
      'New Super Town',
      'Nisbat Road',
      'Nishat Colony',
      'Nishtar Colony',
      'Nizamabad',
      'Noor Jahan Road',
      'OPF Housing Scheme',
      'Officer Colony',
      'Omega Homes',
      'Others',
      'Outfall Road',
      'P & D Housing Society',
      'PAF Colony',
      'PAF Society',
      'PASSCO Housing Society',
      'PCSIR Housing Scheme',
      'PCSIR Staff Colony',
      'PIA Housing Scheme',
      'PIA Main Boulevard',
      'Pak Arab Housing Society',
      'Pak Park',
      'Pakki Thatti',
      'Palm Villas',
      'Paragon City',
      'Park View Villas',
      'Peco Road',
      'Peer Colony',
      'Pine Villas',
      'Pir Naseer',
      'Poonch Road',
      'Prem Nagar',
      'Prime Homes 1',
      'Public Health Society',
      'Punjab Coop Housing Society',
      'Punjab Govt Employees Society',
      'Punjab Govt Servant Society',
      'Punjab Small Industries Colony',
      'Punjab University Employees Society',
      'Qadri Colony',
      'Qartaba Chowk',
      'Qasurpura',
      'Qazi Town',
      'Qilla Gujjar Singh',
      'Queens Road',
      'Race Course Road',
      'Rail Town (Canal City)',
      'Railway Officers Colony',
      'Raiwind Road',
      'Raj Garh',
      'Rajgarh Road',
      'Rajpoot Town',
      'Rana Shaukat Mehmood Road',
      'Rana Town',
      'Rang Mahal',
      'Rasool Park',
      'Ravi Park',
      'Ravi Road',
      'Real Cottages',
      'Rehan Garden',
      'Rehman City - Phase 4',
      'Rehman Gardens',
      'Rehman Housing Society',
      'Rehman Park',
      'Rehman Villas',
      'Rehmanpura (Ferozpur Road)',
      'Rehmanpura (Harbanspura)',
      'Revenue Society',
      'Rewaz Garden',
      'Rifle Range Road',
      'Ring Road',
      'River View Coop Housing Society',
      'Riwaz Garden',
      'Rizwan Garden Scheme',
      'Royal Garden',
      'Royal Residencia',
      'Rustam Park',
      'Saadat Avenue',
      'Saadi Park',
      'Sabzazar Scheme',
      'Sadaat Town',
      'Saggian',
      'Saggian Wala Bypass Road',
      'Sahafi Colony',
      'Saiden Shah Colony',
      'Saidpur',
      'Sajid Garden',
      'Salamatpura',
      'Salli Town',
      'Sally Town South',
      'Saman Berg',
      'Samanabad',
      'Samanzar Colony',
      'Sami Town',
      'Samsani Road',
      'Sanda',
      'Sanda Road',
      'Sant Nagar',
      'Saqib Town',
      'Saraich',
      'Saroba Gardens Housing Society',
      'Sarwar Town',
      'Shadab Garden',
      'Shadbagh',
      'Shadipura',
      'Shadman 1',
      'Shadman 2',
      'Shah Di Khoi',
      'Shah Faisal Road',
      'Shah Jamal',
      'Shah Kamal Road',
      'Shah Khawar Town',
      'Shahdara',
      'Shahkam Chowk',
      'Shahpur Kanjra',
      'Shahtaj Colony',
      'Shalimar Housing Scheme',
      'Shalimar Link Road',
      'Shalimar Town',
      'Sham Nagar',
      'Shama Road',
      'Shamkay Bhattian',
      'Shanghai Road',
      'Sharaqpur Road',
      'Sheikhupura Road',
      'Sher Shah Road',
      'Shera Kot',
      'Sheraz Town',
      'Shershah Colony - Ichra',
      'Shershah Colony - Raiwind Road',
      'Sherwani Town Housing Scheme',
      'Shiraz Villas',
      'Shoukat Town',
      'Shuja Road',
      'Siddiqia Colony',
      'Siddiqia Society (College Road)',
      'Sikandar Road',
      'Singhpura',
      'Sitara Colony',
      'Sodiwal',
      'Sozo Town',
      'State Life Housing Society',
      'Sue-e-Asal',
      'Sufiabad',
      'Sui Gas Employees Cooperative Housing Society',
      'Sui Gas Housing Society',
      'Sukh Chayn Gardens',
      'Sultan Colony',
      'Sultan Pura',
      'Sultan Town',
      'Sundar',
      'Sundar Road',
      'Sunderdas Road',
      'Sunflower Housing Society',
      'Sunfort Gardens',
      'Sunny Park',
      'Super Town',
      'Supreme Villas',
      'Swami Nagar',
      'T & T Aabpara Housing Society',
      'TECH Society',
      'TIP Housing Society',
      'Taj Bagh Scheme',
      'Tajpura',
      'Tariq Gardens',
      'Tariq Ismail Road',
      'Tarogill',
      'Temple Road',
      'Thethar',
      'Thokar Niaz Baig',
      'Toheed Park',
      'Township',
      'Tricon Village',
      'Tulspura',
      'UBL Housing Society',
      'UET Housing Society',
      'UMT Society',
      'Upper Mall',
      'Urdu Bazar',
      'Valencia Housing Society',
      'Venus Housing Scheme',
      'Vital Homes Housing Scheme',
      'Wafaqi Colony',
      'Wahdat Colony',
      'Wahdat Road',
      'Walled City',
      'Walton Railway Officers Colony',
      'Walton Road',
      'Wapda Colony',
      'Wapda Town',
      'Waris Colony',
      'Waris Road',
      'Wassanpura',
      'West Wood Housing Society',
      'Wocland Villas',
      'Wyeth Employees Coop Housing',
      'Yazdani Road',
      'Youhanabad',
      'Zaheer Villas',
      'Zaitoon - New Lahore City',
      'Zaitoon Colony',
      'Zaman Colony',
      'Zaman Park',
      'Zubaida Park',
    ],
    'Rawalpindi': [
      'Abdullah City',
      'Abid Majeed Road',
      'Adiala Road',
      'Affandi Colony',
      'Afshan Colony',
      'Ahmad Abad',
      'Air Force Housing Society',
      'Airport Housing Society',
      'Airport Road',
      'Akalgarh',
      'Al-Haram City - Phase 2',
      'Al-Noor Colony',
      'Ali Abad',
      'Ali Town',
      'Allahabad Road',
      'Allama Iqbal Colony',
      'Amarpura',
      'Ameen Town',
      'Amer Pura',
      'Aria Mohalla',
      'Army Officers Colony',
      'Asghar Mall Road',
      'Ashraf Colony',
      'Askari 1',
      'Askari 10',
      'Askari 11',
      'Askari 12',
      'Askari 13',
      'Askari 14',
      'Askari 15',
      'Askari 2',
      'Askari 3',
      'Askari 4',
      'Askari 5',
      'Askari 7',
      'Askari 8',
      'Askari 9',
      'Aslam Shaheed Road',
      'Awan Town',
      'Ayub Colony',
      'Ayub National Park',
      'Azeem Town',
      'Azizabad',
      'Babar Colony',
      'Badar Colony',
      'Bagh Sardaran',
      'Bahar Colony',
      'Bahria Town Rawalpindi',
      'Bakra Mandi',
      'Banaras Colony',
      'Bangash Colony',
      'Bankers Colony',
      'Banni Chowk',
      'Bethsaida Colony',
      'Bilal Colony',
      'Bostan Road',
      'Bostan Valley',
      'CBR Town Phase 2',
      'CMH Road',
      'Caltex Road',
      'Cantt',
      'Capital Awami Villas',
      'Capital Smart City',
      'Chah Sultan',
      'Chakbeli Road',
      'Chaklala',
      'Chaklala Scheme',
      'Chakra',
      'Chakra Road',
      'Chakri',
      'Chakri Road',
      'Chandni Chowk',
      'Chanman Abad',
      'Chaudhary Jan Colony',
      'Chaudhary Wilayat Khan Road',
      'Chungi No. 22 Road',
      'Chur Chowk',
      'City Villas',
      'Civil Lines',
      'Clifton Township',
      'College Road',
      'Commercial Market',
      'Committee Chowk',
      'Cricket Stadium Road',
      'DAV College Road',
      'Data Ganj Bakhsh Road',
      'Defence Colony',
      'Defence Road',
      'Dhamyal Road',
      'Dheri Hassanabad',
      'Dhok Babu Irfan',
      'Dhok Chiragh Din',
      'Dhok Elahi Baksh',
      'Dhok Gujran',
      'Dhok Hukamdad',
      'Dhok Kala Khan',
      'Dhok Kashmirian',
      'Dhok Mangtal',
      'Dhok Mustaqeem Road',
      'Dhok Naju',
      'Dhok Paracha',
      'Dhok Piran Faqiran',
      'Dhok Sayedan Road',
      'Dhoke Banaras Road',
      'Dhoke Dalal Road',
      'Dhoke Gangal',
      'Dhoke Hassu',
      'Dhoke Khabba',
      'Dhoke Munshi Khan',
      'Dhoke Ratta',
      'Dhoke Syedan',
      'Doctors Housing Society',
      'Eastridge Housing Scheme',
      'Faisal Colony',
      'Faizabad',
      'Farooq-e-Azam Road',
      'Fazaia Colony',
      'Fazal Town',
      'Firdosi Road',
      'Friends Colony',
      'G. H. Q',
      'GT Road',
      'Gangaal',
      'Garja',
      'Gawal Mandi',
      'Ghauri Town',
      'Ghaziabad',
      'Ghous-e-Azam Road',
      'Ghousia Colony',
      'Girja Road',
      'Gorakhpur',
      'Gulbahar Scheme',
      'Gulistan Colony',
      'Gulistan Fatima Colony',
      'Gulistan-e-Jinnah Colony',
      'Gulraiz Housing Scheme',
      'Gulshan Abad',
      'Gulshan Dadan',
      'Gulshan-e-Iqbal',
      'Gulshan-e-Saeed',
      'Gulshan-e-Safeer',
      'Gulshan-e-Shamal',
      'Gulshan-e-Zaheer Colony',
      'Gulzar-e-Quaid Housing Society',
      'Haji Chowk',
      'Hakim Muhammad Ajmal Khan Road',
      'Harley Street',
      'Hazara Colony',
      'High Court Road',
      'Holy Family Road',
      'Humak',
      'Ideal Homes Society',
      'Imam Bara Road',
      'Islamabad Farm Houses',
      'Islamabad Highway',
      'Jamia Masjid Road',
      'Janjua Town',
      'Jarahi',
      'Jhanda Chichi',
      'Jinnah Colony',
      'Judicial Colony',
      'Jumma Market',
      'KRL Road',
      'Kacheri Chowk',
      'Kahuta',
      'Kallar Syedan',
      'Kalma Chowk',
      'Kamala Abad',
      'Kartar Pura',
      'Khanna Road',
      'Khayaban-e-Faisal',
      'Khayaban-e-Sir Syed',
      'Khayaban-e-Tanveer',
      'Khurram Colony',
      'Kingdom Valley Islamabad',
      'Kiyani Road',
      'Kohati Bazar',
      'Kurri Road',
      'Lakhu Road',
      'Lalarukh Colony',
      'Lalazar',
      'Lalazar 2',
      'Lalkurti',
      'Liaquat Bagh',
      'Liaquat Colony',
      'Magistrate Colony',
      'Malik Colony',
      'Mall Road',
      'Mangral Town',
      'Marir',
      'Marir Hassan',
      'Media Town',
      'Misryal Road',
      'Model Colony',
      'Model Town Humak',
      'Mohallah Raja Sultan',
      'Mohammadi Colony',
      'Mohan Pura',
      'Momin Pura',
      'Morgah',
      'Mughal Abad Road',
      'Mumtaz Colony',
      'Munawar Colony',
      'Murree Road',
      'Muslim Town',
      'Nanak Pura',
      'Naseerabad',
      'National Garden Housing Scheme',
      'Nawaz Colony',
      'New Afzal Town',
      'New Katarian',
      'New Lalazar',
      'Nussah Town',
      'Others',
      'PAF Residential Area',
      'PIA Colony',
      'PWD Colony',
      'Palm City',
      'Park View',
      'Peer Meher Ali Shah Town',
      'People Colony',
      'Peshawar Road',
      'Pindora',
      'Pir Wadhai',
      'Police Foundation Housing Scheme',
      'Professors Colony',
      'Punjab Government Servant Housing Foundation (PGSHF)',
      'Qasimabad',
      'Quaid-e-Azam Colony',
      'Race Course',
      'Raheemabad',
      'Rail View Housing Society',
      'Railway Scheme 9',
      'Raja Bazar',
      'Range Road',
      'Ranial',
      'Rawal Road',
      'Rawalpindi, Punjab',
      'Rawat',
      'Rawat Enclave',
      'Rawat Industrial Estate',
      'Rehmanabad',
      'Riaz Qureshi Road',
      'Sabzazar',
      'Saddar',
      'Sadiqa Abad',
      'Sadiqabad',
      'Safari View Residencia',
      'Saidpur Road',
      'Samarzar Housing Society',
      'Sangar Town',
      'Sarafa Bazar',
      'Sarwar Road',
      'Satellite Town',
      'Shah Khalid Colony',
      'Shaheen Town',
      'Shakrial',
      'Shalley Valley',
      'Shams Abad',
      'Sher Zaman Colony',
      'Sir Syed Chowk',
      'Sir Syed Road',
      'Stadium Road',
      'T & T Colony',
      'Taj Residencia',
      'Takht Pari',
      'Tali Mori',
      'Tench Bhata',
      'Tench Road',
      'Tipu Road',
      'Transformer Chowk',
      'Tulsa',
      'Tulsa Road',
      'Wah Link Road',
      'Walait Homes',
      'Waris Khan',
      'Wazir Town',
      'Westridge',
      'Wireless Residential Colony',
      'Yousaf Colony',
      'Zafar ul Haq Road',
      'Zeeshan Colony',
    ],
  },
  'Sindh': {
    'Karachi': [
      'APP Employees Co-operative Housing Society',
      'ASF Housing Scheme',
      'ASF Tower',
      'Abdullah Ahmed Road',
      'Abdullah Haroon Road',
      'Abid Town',
      'Abul Hassan Isphani Road',
      'Ahsan Grand City',
      'Airport',
      'Aisha Manzil',
      'Al-Hilal Society',
      'Al-Jadeed Residency',
      'Al-Manzar Society',
      'Al-Safaa Garden',
      'Allama Iqbal Town',
      'Altaf Hussain Road',
      'Amil Colony',
      'Amir Khusro',
      'Anda Mor Road',
      'Azam Town',
      'BMCHS',
      'Bagh-e-Korangi',
      'Bahria Town Karachi',
      'Baldia Town',
      'Baloch Colony',
      'Bath Island',
      'Beaumont Road',
      'Bilal Town',
      'Bin Qasim Town',
      'Blue Bell Residency',
      'Britto Road',
      'Cantt',
      'Catholic Colony',
      'Chapal Courtyard',
      'Chapal Skymark',
      'Chapal Uptown',
      'Civil Lines',
      'Clifton',
      'Cosmopolitan Society',
      'Cotton Export Cooperative Housing Society',
      'Cutchi Memon Cooperative Housing Society',
      'DHA City Karachi',
      'DHA Defence',
      'Dalmia Cement Factory Road',
      'Damba',
      'Darul Aman Society',
      'Dastgir Colony',
      'Defence Garden',
      'Defence View Society',
      'Delhi Colony',
      'Dhabeji',
      'Diamond City',
      'Dr Daud Pota Road',
      'Erum Villas',
      'Etawa Society',
      'Falaknaz Dynasty',
      'Falaknaz Presidency',
      'Falcon Complex Faisal',
      'Fazaia Housing Scheme',
      'Federal B Area',
      'Frere Town',
      'Gadap Road',
      'Gadap Town',
      'Garden West',
      'Gizri',
      'Gizri Road',
      'Gobal Town',
      'Golimar',
      'Goth Ibrahim Haidri',
      'Gujjar Chowk',
      'Gulberg Town',
      'Gulistan-e-Jauhar',
      'Gulistan-e-Malir',
      'Gulshan-E-Faisal',
      'Gulshan-e-Amin',
      'Gulshan-e-Areesha',
      'Gulshan-e-Ghazian',
      'Gulshan-e-Iqbal Town',
      'Gulshan-e-Jami',
      'Gulshan-e-Malir',
      'Gulshan-e-Millat',
      'Gulshan-e-Umair',
      'Gulshan-e-Usman Housing Society',
      'Guru Mandir Chorangi',
      'Hassan Goth',
      'Hawks Bay Scheme 42',
      'Hill Park',
      'Hoshang Road',
      'Hub River Road',
      'Humaira Town',
      'I. I. Chundrigar Road',
      'Intelligence Colony',
      'Jamaluddin Afghani Road',
      'Jamshed Road',
      'Jamshed Town',
      'Javed Bahria Coopretive Housing Society',
      'Jinnah Avenue',
      'KDA Scheme 1',
      'Kamran Chowrangi',
      'Karachi Golf City',
      'Karachi Motorway',
      'Karachi, Sindh',
      'Kashmir Colony',
      'Kashmir Road',
      'Kemari Town',
      'Khalid Bin Walid Road',
      'Khaliq-uz-Zaman Road',
      'Khayaban-e-Ittehad Road',
      'Khuda Ki Basti',
      'Khudadad Colony',
      'Korangi',
      'Korangi Road',
      'Lalukhet',
      'Landhi',
      'Laraib Garden',
      'Liaquat Avenue',
      'Liaquatabad',
      'Lines Area',
      'Lyari Expressway',
      'Lyari Town',
      'M. A. Jinnah Road',
      'MT Khan Road',
      'Malir',
      'Malir Housing Scheme 1',
      'Malir Link To Super Highway',
      'Manghopir Road',
      'Mangopir',
      'Manzoor Colony',
      'Maqboolabad Society',
      'Maskan Chowrangi',
      'Mauripur Road',
      'Mehmoodabad',
      'Muslimabad Society',
      'National Highway',
      'Naval Colony',
      'Naval Housing Scheme',
      'Navy Housing Scheme Karsaz',
      'Naya Nazimabad',
      'Nazimabad',
      'New Karachi',
      'Nishtar Road (Lawrence Road)',
      'Nooriabad',
      'North Karachi',
      'North Nazimabad',
      'Northern Bypass',
      'Numaish Chowrangi',
      'Old Clifton',
      'Old Queens Road',
      'Old Ravians Co-Operative Housing Society',
      'Orangi Town',
      'Others',
      'P & T Colony',
      'PAF Housing Scheme',
      'PIDC',
      'PTV Society',
      'Pakistan Chowk',
      'Peoples Colony',
      'Police Society',
      'Punjab Chowrangi',
      'Punjab Colony',
      'Qayyumabad',
      'Rabia City',
      'Ranchore Line Bazar',
      'Rashid Minhas Road',
      'Royal Defence Tower',
      'Rufi Lake Drive Apartments',
      'Rufi Rose Petals',
      'Saadi Road',
      'Saddar Town',
      'Saima Luxury Homes',
      'Sakhi Hassan Chowrangi',
      'Scheme 33',
      'Scheme 45',
      'Sea View Apartments',
      'Shadman 2',
      'Shah Faisal Town',
      'Shah Rasool Colony',
      'Shah Town',
      'Shaheed Millat Road',
      'Shaheed-e-Millat Expressway',
      'Shahra-e-Faisal',
      'Shahra-e-Jahangir',
      'Shahra-e-Liaquat',
      'Shahra-e-Qaideen',
      'Shahra-e-Usman',
      'Shahrah-e-Pakistan',
      'Sher Shah Suri Road',
      'Sindh Industrial Trading Estate (SITE)',
      'Siraj-ud-Daula Road',
      'Stadium Road',
      'State Bank of Pakistan Staff Co-Operative Housing Society',
      'Suparco Road',
      'Super Highway',
      'Surti Muslim Co-Operative Housing Society',
      'Tahir Villa',
      'Tariq Road',
      'Teacher Society',
      'Teachers Society',
      'Times Residency',
      'Tipu Sultan Road',
      'University Road',
      'Zamzama',
      'circular road',
    ],
  },
};
