const Map<String, Map<String, List<String>>> pakistanGeography = {
  'Punjab': {
    'Lahore': ['Lahore', 'Raiwind', 'Walton', 'Kahna', 'Thokar', 'Shahdara'],
    'Faisalabad': [
      'Faisalabad',
      'Jaranwala',
      'Samundri',
      'Tandlianwala',
      'Chak Jhumra',
      'Dijkot',
    ],
    'Rawalpindi': [
      'Rawalpindi',
      'Murree',
      'Gujar Khan',
      'Kahuta',
      'Kallar Syedan',
      'Kotli Sattian',
      'Taxila',
    ],
    'Multan': [
      'Multan',
      'Shujabad',
      'Jalalpur Pirwala',
      'Bosan',
      'Qadirpur Raan',
    ],
    'Gujranwala': ['Gujranwala', 'Kamoke', 'Nowshera Virkan', 'Eminabad'],
    'Sialkot': ['Sialkot', 'Daska', 'Sambrial', 'Pasrur', 'Uggoki'],
    'Sargodha': ['Sargodha', 'Bhalwal', 'Shahpur', 'Sillanwali', 'Kot Momin'],
    'Bahawalpur': [
      'Bahawalpur',
      'Hasilpur',
      'Yazman',
      'Ahmadpur East',
      'Khairpur Tamewali',
    ],
    'Rahim Yar Khan': ['Rahim Yar Khan', 'Sadiqabad', 'Liaqatpur', 'Khanpur'],
    'Sheikhupura': [
      'Sheikhupura',
      'Muridke',
      'Sharaqpur',
      'Ferozewala',
      'Safdarabad',
    ],
    'Kasur': ['Kasur', 'Pattoki', 'Chunian', 'Kot Radha Kishan', 'Khudian'],
    'Okara': ['Okara', 'Depalpur', 'Renala Khurd', 'Hujra Shah Muqeem'],
    'Sahiwal': ['Sahiwal', 'Chichawatni', 'Noor Shah'],
    'Gujrat': ['Gujrat', 'Kharian', 'Jalalpur Jattan', 'Lalamusa'],
    'Jhelum': ['Jhelum', 'Dina', 'Sohawa', 'Pind Dadan Khan'],
    'Chiniot': ['Chiniot', 'Lalian', 'Bhawana'],
    'Mianwali': ['Mianwali', 'Isa Khel', 'Daud Khel'],
    'Chakwal': ['Chakwal', 'Talagang', 'Choa Saidan Shah', 'Kallar Kahar'],
    'Pakpattan': ['Pakpattan', 'Arifwala'],
    'Vehari': ['Vehari', 'Mailsi', 'Burewala'],
    'Lodhran': ['Lodhran', 'Dunyapur', 'Kehror Pacca'],
    'Bhakkar': ['Bhakkar', 'Darya Khan', 'Kallur Kot', 'Mankera'],
    'Layyah': ['Layyah', 'Karor Lal Esan', 'Chaubara'],
    'Khanewal': ['Khanewal', 'Kabirwala', 'Mian Channu', 'Jahanian'],
    'Muzaffargarh': ['Muzaffargarh', 'Alipur', 'Jatoi', 'Kot Addu'],
    'D.G. Khan': ['Dera Ghazi Khan', 'Taunsa Sharif', 'Kot Chutta'],
    'Bahawalnagar': ['Bahawalnagar', 'Fort Abbas', 'Haroonabad', 'Chishtian'],
    'Nankana Sahib': ['Nankana Sahib', 'Shahkot', 'Sangla Hill', 'Warburton'],
    'Hafizabad': ['Hafizabad', 'Pindi Bhattian'],
    'Narowal': ['Narowal', 'Shakargarh', 'Zafarwal'],
    'Attock': ['Attock', 'Hasan Abdal', 'Fateh Jang', 'Jand'],
    'Toba Tek Singh': ['Toba Tek Singh', 'Gojra', 'Kamalia'],
    'Jhang': ['Jhang', 'Shorkot', 'Ahmedpur Sial'],
    'Khushab': ['Khushab', 'Jauharabad', 'Noshera', 'Hadali'],
    'Mandi Bahauddin': ['Mandi Bahauddin', 'Phalia', 'Malakwal'],
    'Rajanpur': ['Rajanpur', 'Jampur', 'Fazilpur', 'Rojhan'],
  },
  'Sindh': {
    'Karachi Central': [
      'Liaquatabad',
      'Nazimabad',
      'Gulberg',
      'Federal B Area',
      'Karimabad',
    ],
    'Karachi East': [
      'Gulshan-e-Iqbal',
      'Gulistan-e-Jauhar',
      'Bahadurabad',
      'Safoora',
      'Cantt',
    ],
    'Karachi South': [
      'Saddar',
      'Clifton',
      'Defence',
      'Burns Road',
      'Lyari',
      'Kharadar',
    ],
    'Karachi West': ['Orangi Town', 'Baldia Town', 'SITE', 'Manghopir'],
    'Korangi': ['Korangi', 'Landhi', 'Shah Faisal Colony', 'Model Colony'],
    'Malir': ['Malir', 'Shah Latif Town', 'Quaidabad', 'Bin Qasim'],
    'Hyderabad': ['Hyderabad City', 'Qasimabad', 'Latifabad', 'Tando Jam'],
    'Sukkur': ['Sukkur', 'Rohri', 'Pano Aqil'],
    'Larkana': ['Larkana', 'Ratodero', 'Dokri', 'Bakrani'],
    'Mirpurkhas': [
      'Mirpurkhas',
      'Jhuddo',
      'Sindhri',
      'Digri',
      'Kot Ghulam Muhammad',
    ],
    'Nawabshah': ['Nawabshah', 'Sakrand', 'Daur', 'Qazi Ahmed'],
    'Badin': ['Badin', 'Tando Bago', 'Matli', 'Talhar', 'Khoski'],
    'Thatta': ['Thatta City', 'Mirpur Sakro', 'Keti Bander', 'Gharo'],
    'Sujawal': ['Sujawal', 'Jati', 'Shah Bunder', 'Chuhar Jamali'],
    'Khairpur': [
      'Khairpur',
      'Kot Diji',
      'Mirwah',
      'Gambat',
      'Sobhodero',
      'Hingorja',
    ],
    'Jacobabad': ['Jacobabad', 'Thul', 'Garhi Khairo'],
    'Shikarpur': ['Shikarpur', 'Khanpur', 'Lakhi', 'Garhi Yasin'],
    'Tando Allahyar': ['Tando Allahyar', 'Chamber', 'Jhando Mari'],
    'Tando M. Khan': [
      'Tando Muhammad Khan',
      'Bulri Shah Karim',
      'Tando Ghulam Hyder',
    ],
    'Umerkot': ['Umerkot', 'Samaro', 'Kunri', 'Pithoro'],
    'Dadu': ['Dadu', 'Johi', 'Khairpur Nathan Shah', 'Mehar', 'Sehwan Sharif'],
    'Matiari': ['Matiari', 'Hala', 'Saeedabad'],
    'Sanghar': [
      'Sanghar',
      'Shahdadpur',
      'Tando Adam',
      'Khipro',
      'Sinjhoro',
      'Jam Nawaz Ali',
    ],
    'Ghotki': ['Ghotki', 'Mirpur Mathelo', 'Ubauro', 'Khanpur Mahar'],
    'Kashmore': ['Kashmore', 'Kandhkot', 'Tangwani'],
    'Naushahro Feroze': [
      'Naushahro Feroze',
      'Moro',
      'Mehrabpur',
      'Bhiria City',
      'Kandiaro',
    ],
    'Jamshoro': ['Kotri', 'Sehwan', 'Manjhand', 'Thana Bula Khan'],
    'Tharparkar': [
      'Mithi',
      'Islamkot',
      'Chachro',
      'Diplo',
      'Kaloi',
      'Nagarparkar',
    ],
    'K. Shahdadkot': [
      'Shahdadkot',
      'Qubo Saeed Khan',
      'Warah',
      'Miro Khan',
      'Nasirabad',
    ],
  },
  'KPK': {
    'Peshawar': [
      'Peshawar City',
      'Tehkal',
      'Hayatabad',
      'Chamkani',
      'Badaber',
      'Palosi',
      'Shaheen Town',
      'Pishtakhara',
    ],
    'Mardan': [
      'Mardan City',
      'Takht Bhai',
      'Katlang',
      'Rustam',
      'Baghdada',
      'Gujar Garhi',
      'Lund Khwar',
    ],
    'Swat': [
      'Mingora',
      'Saidu Sharif',
      'Matta',
      'Kabal',
      'Bahrain',
      'Kalam',
      'Fizagat',
      'Charbagh',
      'Utror',
    ],
    'Abbottabad': [
      'Abbottabad',
      'Havelian',
      'Lora',
      'Sheikhul Bandi',
      'Salhad',
      'Qalandarabad',
    ],
    'Mansehra': [
      'Mansehra',
      'Balakot',
      'Oghi',
      'Baffa',
      'Shinkiari',
      'Garhi Habibullah',
      'Kaghan',
      'Naran',
    ],
    'Haripur': [
      'Haripur City',
      'Khanpur',
      'Ghazi',
      'Sirikot',
      'Hattar',
      'Kot Najibullah',
    ],
    'Charsadda': [
      'Charsadda',
      'Shabqadar',
      'Tangi',
      'Utmanzai',
      'Rajjar',
      'Nisatta',
      'Sherpao',
    ],
    'Nowshera': [
      'Nowshera City',
      'Akora Khattak',
      'Pabbi',
      'Jehangira',
      'Rashakai',
      'Azakhel',
      'Amangarh',
    ],
    'Swabi': [
      'Swabi City',
      'Topi',
      'Razar',
      'Chota Lahore',
      'Shah Mansoor',
      'Gohati',
      'Yar Hussain',
    ],
    'Kohat': [
      'Kohat City',
      'Lachi',
      'Gumbat',
      'Jarma',
      'Ustarzai',
      'Shakardarra',
    ],
    'Bannu': [
      'Bannu City',
      'Domel',
      'Kakki',
      'Miryan',
      'Ghoriwala',
      'Mandan',
      'Sokari',
    ],
    'D.I. Khan': [
      'D.I. Khan',
      'Kulachi',
      'Paharpur',
      'Chashma Town',
      'Daraban',
      'Paniala',
    ],
    'Lakki Marwat': ['Lakki', 'Serai Naurang', 'Abbasa Khel', 'Tajori', 'Pezu'],
    'Tank': ['Tank City', 'Gomal', 'Muhammadzai', 'Mullazai'],
    'Karak': [
      'Karak City',
      'Banda Daudshah',
      'Takht-e-Nasrati',
      'Latamber',
      'Teri',
      'Jatta Ismail Khel',
    ],
    'Batagram': ['Batagram', 'Allai', 'Kuza Banda', 'Thakot', 'Bana'],
    'Shangla': ['Alpuri', 'Puran', 'Besham', 'Karora', 'Shahpur', 'Chakisar'],
    'Upper Dir': ['Dir Town', 'Wari', 'Thal', 'Barawal', 'Jandari'],
    'Lower Dir': [
      'Timergara',
      'Chakdara',
      'Maidan',
      'Talash',
      'Khall',
      'Munda',
    ],
    'Malakand': ['Batkhela', 'Dargai', 'Thana', 'Alladand', 'Sakhakot'],
    'Buner': ['Daggar', 'Sawari', 'Sultanwas', 'Pir Baba', 'Chinglai'],
    'Hangu': ['Hangu City', 'Thall', 'Doaba', 'Togh Bala'],
    'Orakzai': ['Kalaya', 'Hangu-Orakzai belt', 'Ghiljo', 'Mishti', 'Khanzai'],
    'Kurram': [
      'Parachinar',
      'Sadda',
      'Alizai',
      'Pewar',
      'Tari Mangal',
      'Shalozan',
    ],
    'N. Waziristan': [
      'Miranshah',
      'Mir Ali',
      'Boya',
      'Spinwam',
      'Razmak',
      'Datta Khel',
      'Ghulam Khan',
    ],
    'S. Waziristan': ['Wana', 'Shakai', 'Ladha', 'Makeen', 'Sararogha'],
  },
};
